# Generated by Django 5.0.4 on 2024-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('pregunta_recuperacion', models.CharField(max_length=256)),
                ('respuesta_recuperacion', models.CharField(max_length=100)),
            ],
        ),
    ]
