# Generated by Django 5.0.4 on 2024-04-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('contenido', models.IntegerField()),
                ('unidad_de_medida', models.CharField(max_length=30, verbose_name='unidad_medida')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_barras', models.CharField(max_length=100)),
                ('no_referencia_inv', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField()),
                ('lote', models.CharField(max_length=100)),
                ('fecha_recepcion', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('cod', models.IntegerField()),
                ('status', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
    ]
