# Generated by Django 5.0.4 on 2024-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(related_name='locations', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(related_name='types', to='app.item')),
            ],
        ),
    ]
