# Generated by Django 5.0.4 on 2024-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cod',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_caducidad',
            field=models.DateField(null=True),
        ),
    ]
