# Generated by Django 5.0.4 on 2024-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_registro_cod_alter_registro_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
