# Generated by Django 5.0.4 on 2024-04-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_location_items_remove_type_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Location',
        ),
        migrations.AddField(
            model_name='item',
            name='locations',
            field=models.ManyToManyField(related_name='items', to='app.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(related_name='items', to='app.type'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
