# Generated by Django 5.0.4 on 2024-05-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_item_location_item_locations_alter_item_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='marcas',
            field=models.ManyToManyField(related_name='items', to='app.marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='proveedores',
            field=models.ManyToManyField(related_name='items', to='app.proveedor'),
        ),
    ]
