# Generated by Django 5.0.4 on 2024-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_item_stock_alter_registro_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='numero_registro',
            field=models.IntegerField(default=0),
        ),
    ]
