# Generated by Django 5.0.4 on 2024-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_registro_numero_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
