# Generated by Django 5.0.4 on 2024-05-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_marca_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='usuario',
        ),
    ]
