# Generated by Django 5.0.4 on 2024-06-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='sub_recetas',
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes_items',
            field=models.ManyToManyField(through='app.RecetaItem', to='app.item'),
        ),
        migrations.CreateModel(
            name='RecetaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_principal', to='app.receta')),
                ('subreceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_secundaria', to='app.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes_recetas',
            field=models.ManyToManyField(related_name='subrecetas', through='app.RecetaReceta', to='app.receta'),
        ),
    ]
