# Generated by Django 5.0.4 on 2024-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_location_usuario_type_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
