# Generated by Django 5.0.4 on 2024-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_registro_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='precio',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
