# Generated by Django 5.0.4 on 2024-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_pregunta_recuperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='respuesta_recuperacion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
