# Generated by Django 5.0.4 on 2024-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_plaintext_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pregunta_recuperacion',
            field=models.CharField(choices=[('color', 'Color favorito'), ('animal', 'Animal favorito'), ('apodo', 'Apodo de la infancia'), ('ciudad', 'Ciudad de nacimiento'), ('comida', 'Comida favorita'), ('libro', 'Libro favorito'), ('pelicula', 'Película favorita'), ('cantante', 'Cantante favorito'), ('nombre_madre', 'Nombre de tu madre'), ('nombre_padre', 'Nombre de tu padre'), ('primer_maestro', 'Nombre de tu primer maestro/a'), ('nombre_mascota', 'Nombre de tu primera mascota'), ('lugar_vacaciones', 'Lugar de tus vacaciones favoritas'), ('nombre_abuelo', 'Nombre de tu abuelo/a'), ('mejor_amigo', 'Nombre de tu mejor amigo/a'), ('nombre_colegio', 'Nombre de tu colegio/instituto'), ('fecha_importante', 'Fecha importante para ti'), ('instrumento_musical', 'Instrumento musical favorito'), ('jugador_favorito', 'Jugador deportivo favorito'), ('hobby', 'Hobby o pasatiempo favorito')], default='color', max_length=20),
        ),
    ]
